### ISSUE TITLE
Add employees break tool

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#11]
## Description

Employees can put them self in a queue list to go in break.
For example 2 employees can go in break,  the others need to wait untill one of the 2 employees are out break.
## Todo
- [ ] Create queue list
- [ ] Create break list
- [ ] Add break options (max-break-time, allowed-employees)

**Comment by ghermans** [comment]
preview

![selection_148](https://cloud.githubusercontent.com/assets/1594411/14037308/4e276720-f242-11e5-98b1-8396287fd0c7.png)
