### ISSUE TITLE
Overtime requests

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#12]
## Description

When employees do overtime they have the right to get those hours back.
## Todo
- [ ] Create overtime list
- [ ] Create form to request how many hours / minutes the employee take overtime
- [ ] Send email confirmations to managers and employee
