### ISSUE TITLE
Create documentation portal

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/timecontrol#204]
# TODO:
- [x] Add contributing file
- [x] Add readme labels. 
- [x] Add License 
- [x] Improve index page. 
- [x] Improve installation tutorial. 

**NOTE:** Later on things can be added
