### ISSUE TITLE
call in sick

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#22]
# Description
- When the employee calls in sick this has to be reported to the employee's manager(s).
# Todo
- [x] Create registration form
- [ ] Send confirmation mail to manager(s)
- [ ] Remove all planned tasks for the employee until he/she is back.

**Comment by ghermans** [comment]
Basic pages for tis enhancement have been added.
