### ISSUE TITLE
Change static user img to dynamic

### ISSUE THREAD

**Issue by ghermans** [idevelopment/timecontrol#72]
For the current moment the user avatar is a static file.
## Todo
- [x] Add file input on user forms.
- [ ] Allow users to update there avatar.

**Comment by Tjoosten** [comment]
PR provided but with merge conflict. @ghermans will look after it.

**Comment by ghermans** [comment]
## Todo:
- [ ] Add file field on the form (edit user pages).
- [ ] Upload the new image.
- [ ] Link the image to the user account.

**Comment by Tjoosten** [comment]
I close this one there is a seperate issue for the left over work
